# Generated by Django 2.1 on 2018-08-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.FloatField(),
        ),
    ]
